name: Deploy
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment'
        required: true
        type: string

  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: environment
        required: true

jobs:
  log-the-inputs:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
    steps:
      - run: |
          echo "Environment: $ENVIRONMENT"
          echo "NEXT_PUBLIC_ENV: $NEXT_PUBLIC_ENV"
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          NEXT_PUBLIC_ENV: ${{ secrets.NEXT_PUBLIC_ENV }}
